version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: test_rdbs
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: cv
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-local:
    image: 'redis:latest'
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
